//User reducers
export const SET_AUTHENTICATED = 'SET_AUTHENTICATED';
export const SET_UNAUTHENTICATED = 'SET_UNAUTHENTICATED';
export const SET_USER = 'SET_USER';
export const LOADING_USER = 'LOADING_USER';
export const MARK_NOTIFICATIONS_READ = 'MARK_NOTIFICATIONS_READ';
//UI Reducers
export const SET_ERROR = 'SET_ERROR';
export const LOADING_UI = 'LOADING_UI';
export const CLEAR_ERROR = 'CLEAR_ERROR';
export const LOADING_DATA = 'LOADING_DATA';
export const STOP_LOADING_UI = 'STOP_LOADING_UI';
export const SET_MESSAGE = 'SET_MESSAGE';
export const CLEAR_MESSAGE = 'CLEAR_MESSAGE';
export const CHANGE_TYPE = 'CHANGE_TYPE';

//Data Reducers
export const GET_SCREAMS = "GET_SCREAMS";
export const GET_SCREAM = 'GET_SCREAM';
export const LIKE_SCREAM = 'LIKE_SCREAM';
export const UNLIKE_SCREAM = 'UNLIKE_SCREAM';
export const DELETE_SCREAM = 'DELETE_SCREAM';
export const POST_SCREAM = 'POST_SCREAM';
export const SUBMIT_COMMENT = 'SUBMIT_COMMENT';
export const GET_SCREAMS_BY_USER = 'GET_SCREAMS_BY_USER';
export const EDIT_SCREAM = 'EDIT_SCREAM';
export const GET_NUMBER_SCREAMS = 'GET_NUMBER_SCREAMS';
export const GET_SCREAMS_BY_PAGE = 'GET_SCREAMS_BY_PAGE';
export const CLEAR_SCREAM = 'CLEAR_SCREAM';