//User reducers
export const SET_AUTHENTICATED = 'SET_AUTHENTICATED';
export const SET_UNAUTHENTICATED = 'SET_UNAUTHENTICATED';
export const SET_USER = 'SET_USER';
export const LOADING_USER = 'LOADING_USER';
export const MARK_NOTIFICATIONS_READ = 'MARK_NOTIFICATIONS_READ';
export const MARK_NOTIFICATIONS_READ_SUCCESS = 'MARK_NOTIFICATIONS_READ_SUCCESS';
export const LOGIN_USER = 'LOGIN_USER';
export const SIGNUP_USER = 'SIGNUP_USER';
export const GET_USER_DATA = 'GET_USER_DATA';
export const LOGOUT_USER = 'LOGOUT_USER';
export const AUTH_CHECK_STATE = 'AUTH_CHECK_STATE';
export const CHANGE_AVATAR = 'CHANGE_AVATAR';
export const EDIT_USER = 'EDIT_USER';

//UI Reducers
export const SET_ERROR = 'SET_ERROR';
export const LOADING_UI = 'LOADING_UI';
export const CLEAR_ERROR = 'CLEAR_ERROR';
export const LOADING_DATA = 'LOADING_DATA';
export const STOP_LOADING_UI = 'STOP_LOADING_UI';
export const SET_MESSAGE = 'SET_MESSAGE';
export const CLEAR_MESSAGE = 'CLEAR_MESSAGE';
export const CHANGE_TYPE = 'CHANGE_TYPE';

//Data Reducers
export const GET_SCREAMS = "GET_SCREAMS";
export const GET_SCREAM_START = 'GET_SCREAM_START';
export const GET_SCREAM_SUCCESS = 'GET_SCREAM_SUCCESS';
export const LIKE_SCREAM = 'LIKE_SCREAM';
export const LIKE_SCREAM_SUCCESS = 'LIKE_SCREAM_SUCCESS';
export const UNLIKE_SCREAM = 'UNLIKE_SCREAM';
export const UNLIKE_SCREAM_SUCCESS = 'UNLIKE_SCREAM_SUCCESS';
export const DELETE_SCREAM = 'DELETE_SCREAM';
export const DELETE_SCREAM_SUCCESS = 'DELETE_SCREAM_SUCCESS';
export const POST_SCREAM = 'POST_SCREAM';
export const POST_SCREAM_SUCCESS = 'POST_SCREAM_SUCCESS';
export const SUBMIT_COMMENT = 'SUBMIT_COMMENT';
export const SUBMIT_COMMENT_SUCCESS = 'SUBMIT_COMMENT_SUCCESS';
export const EDIT_SCREAM = 'EDIT_SCREAM';
export const EDIT_SCREAM_SUCCESS = 'EDIT_SCREAM_SUCCESS';
export const GET_NUMBER_SCREAMS = 'GET_NUMBER_SCREAMS';
export const GET_NUMBER_SCREAMS_SUCCESS = 'GET_NUMBER_SCREAMS_SUCCESS';
export const GET_SCREAMS_BY_PAGE_START = 'GET_SCREAMS_BY_PAGE_START';
export const GET_SCREAMS_BY_PAGE_SUCCESS = 'GET_SCREAMS_BY_PAGE_SUCCESS';
export const CLEAR_SCREAM = 'CLEAR_SCREAM';

//Other User
export const GET_OTHER_USER = 'GET_OTHER_USER';
export const LOADING_OTHER_USER = 'LOADING_OTHER_USER';
export const GET_OTHER_USER_SUCCESS = 'GET_OTHER_USER_SUCCESS';
export const GET_SCREAMS_BY_USER = 'GET_SCREAMS_BY_USER';
export const GET_SCREAMS_BY_USER_SUCCESS = 'GET_SCREAMS_BY_USER_SUCCESS';
export const GET_NUMBER_SCREAMS_BY_USER = 'GET_NUMBER_SCREAMS_BY_USER';
export const GET_NUMBER_SCREAMS_BY_USER_SUCCESS = 'GET_NUMBER_SCREAMS_BY_USER_SUCCESS';